// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efproyecto;

#nullable disable

namespace efproyecto.Migrations
{
    [DbContext(typeof(TareasContext))]
    partial class TareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("efproyecto.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("4afb6792-125d-4a8d-8727-d756a620b611"),
                            Description = "Categoría de deportes",
                            Title = "Deporte"
                        },
                        new
                        {
                            CategoryId = new Guid("4afb6792-125d-4a8d-8727-d756a620b612"),
                            Description = "Categoría de estudios",
                            Title = "Estudios"
                        });
                });

            modelBuilder.Entity("efproyecto.Models.Todo", b =>
                {
                    b.Property<Guid>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TodoPriority")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("TodoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TodoId = new Guid("09aa00ba-6e45-49ab-819a-c6ed88d51991"),
                            CategoryId = new Guid("4afb6792-125d-4a8d-8727-d756a620b611"),
                            CreationDate = new DateTime(2022, 12, 11, 14, 4, 34, 531, DateTimeKind.Local).AddTicks(6182),
                            Description = "Cinta y ejercicios de hombros",
                            Title = "Ir al gimnasio",
                            TodoPriority = 0,
                            Weight = 2
                        },
                        new
                        {
                            TodoId = new Guid("09aa00ba-6e45-49ab-819a-c6ed88d51992"),
                            CategoryId = new Guid("4afb6792-125d-4a8d-8727-d756a620b612"),
                            CreationDate = new DateTime(2022, 12, 11, 14, 4, 34, 531, DateTimeKind.Local).AddTicks(6223),
                            Description = "Repasar para entender mejor las bases",
                            Title = "Repasar curso APIs con .NET",
                            TodoPriority = 2,
                            Weight = 1
                        });
                });

            modelBuilder.Entity("efproyecto.Models.Todo", b =>
                {
                    b.HasOne("efproyecto.Models.Category", "Category")
                        .WithMany("Todos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("efproyecto.Models.Category", b =>
                {
                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
